"""`leadradar init --describe "..."`: Claude turns a plain-language description
of your business into a ready-to-run config (offer, buyer phrases per source,
subreddits, exclusions…), so LeadRadar works for any trade: SEO, email
marketing, web design, bookkeeping, video editing, translation…"""

from __future__ import annotations

import copy

import anthropic
import yaml
from pydantic import BaseModel, Field

SYSTEM = """You configure LeadRadar, a tool that finds public posts where people ask for help a
professional sells, and scores them for buying intent. Given a description of the business,
produce search settings that maximise *buyers asking for help* and minimise noise (vendors
self-promoting, news, students, job seekers).

Guidelines:
- Write in the languages of the target markets (e.g. Spanish for Spain/LatAm, English for
  global/remote). If unsure, mix Spanish and English.
- `queries`: 10-16 natural phrases a BUYER would actually write when looking for this help
  ("busco a alguien que me haga el SEO", "recommend an email marketing agency", "my Shopify
  store gets no traffic"). Include problem statements, not just service names. 2-7 words each.
- `keywords`: 5-8 very short topical terms (1-3 words) for keyword search APIs that have no
  intent understanding (Bluesky, Hacker News); the scorer filters intent later.
- `job_board_queries`: 4-6 short skill-style queries for freelance marketplaces.
- `linkedin_queries`: 4-6 short phrases that would appear in LinkedIn posts asking for this help.
- `subreddits`: 5-10 real, active subreddits where these buyers ask (no "r/" prefix).
- `exclude`: phrases that signal noise for this trade (self-promotion, hiring full-time, courses…).
- `extra_sites`: 0-4 domains/paths of niche forums or communities where these buyers ask
  (e.g. "community.shopify.com"). Only real sites.
- `offer`, `ideal_client`, `not_a_fit`: concise, concrete, in the professional's language.
- `tone`: how replies should sound, in the professional's language.
- `report_language`: ISO code of the professional's language.
- `workana`: true if Spanish-speaking clients (Spain or LatAm) are a target market."""


class Generated(BaseModel):
    offer: str
    ideal_client: str
    not_a_fit: str
    tone: str
    report_language: str = Field(description="ISO 639-1 code, e.g. es")
    queries: list[str]
    keywords: list[str]
    job_board_queries: list[str]
    linkedin_queries: list[str]
    subreddits: list[str]
    exclude: list[str]
    extra_sites: list[str]
    bluesky_langs: list[str] = Field(description="ISO codes of the target markets' languages")
    workana: bool


def generate(description: str, example: dict, model: str = "claude-opus-5-5") -> dict:
    client = anthropic.Anthropic()
    response = client.beta.messages.parse(
        model=model,
        max_tokens=8000,
        system=SYSTEM,
        messages=[{"role": "user", "content": f"<business>\n{description.strip()}\n</business>"}],
        output_format=Generated,
        output_config={"effort": "medium"},
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
    )
    if response.stop_reason == "refusal" or response.parsed_output is None:
        raise SystemExit(f"Could not generate a config ({response.stop_reason}). Try rephrasing, or edit config.example.yaml by hand.")
    g = response.parsed_output

    cfg = copy.deepcopy(example)
    cfg["profile"].update(
        offer=g.offer.strip() + "\n",
        ideal_client=g.ideal_client.strip() + "\n",
        not_a_fit=g.not_a_fit.strip() + "\n",
        tone=g.tone,
        report_language=g.report_language,
    )
    cfg["queries"] = g.queries
    cfg["exclude"] = g.exclude
    src = cfg["sources"]
    src["hackernews"]["queries"] = g.keywords
    src["bluesky"]["queries"] = g.keywords
    src["bluesky"]["langs"] = g.bluesky_langs
    src["reddit"]["subreddits"] = g.subreddits
    src["freelancer"]["queries"] = g.job_board_queries
    src["workana"]["queries"] = g.job_board_queries
    src["workana"]["enabled"] = g.workana
    src["apify"]["queries"] = g.linkedin_queries
    sites = src["web"]["sites"]
    src["web"]["sites"] = sites + [s for s in g.extra_sites if s not in sites]
    return cfg


def dump(cfg: dict, description: str) -> str:
    header = (
        "# LeadRadar config generated by `leadradar init --describe`.\n"
        f"# Business: {' '.join(description.split())[:200]}\n"
        "# Every option is explained in config.example.yaml. Review the queries — you know your buyers best.\n\n"
    )
    return header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True, width=100)
